### ISSUE TITLE
findin function not working for dates

### ISSUE THREAD

**Issue by cgroll** [quinnj/Datetime.jl#49]
finding indices of intersecting days in two date arrays is not working. for

``` julia
using Datetime
a = [date(1995, 05, ii) for ii=1:11]
b = [date(1995, 05, ii) for ii=5:31]
```

we get

``` julia
julia> findin(a, b)
0-element Array{Int64,1}
```

although there clearly should be an intersection:

``` julia
julia> intersect(a, b)
7-element Array{Date{C<:Calendar},1}:
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11
```

Another example would be

``` julia
a = [date(1995, 05, ii) for ii=2:31]
b = [date(1995, 05, ii) for ii=5:21]
```

with

``` julia
julia> findin(a, b)
6-element Array{Int64,1}:
 15
 16
 17
 18
 19
 20
```

and

``` julia
julia> intersect(a, b)
17-element Array{Date{C<:Calendar},1}:
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11
 1995-05-12
 1995-05-13
 1995-05-14
 1995-05-15
 1995-05-16
 1995-05-17
 1995-05-18
 1995-05-19
 1995-05-20
 1995-05-21
```

**Comment by quinnj** [comment]
Hmmm..........this may have been fixed when I pushed an update yesterday? Try doing a `Pkg.update()` to pull in the latest version bump and see if it works for you. Below is my output running your commands:

``` julia
In  [3]: using Datetime
a = [date(1995, 05, ii) for ii=1:11]
b = [date(1995, 05, ii) for ii=5:31]

Out [3]: 27-element Array{Date{C<:Calendar},1}:
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11
 1995-05-12
 1995-05-13
 1995-05-14
 1995-05-15
 1995-05-16
 1995-05-17
 ⋮         
 1995-05-20
 1995-05-21
 1995-05-22
 1995-05-23
 1995-05-24
 1995-05-25
 1995-05-26
 1995-05-27
 1995-05-28
 1995-05-29
 1995-05-30
 1995-05-31

In  [4]: a

Out [4]: 11-element Array{Date{C<:Calendar},1}:
 1995-05-01
 1995-05-02
 1995-05-03
 1995-05-04
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11

In  [5]: b

Out [5]: 27-element Array{Date{C<:Calendar},1}:
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11
 1995-05-12
 1995-05-13
 1995-05-14
 1995-05-15
 1995-05-16
 1995-05-17
 ⋮         
 1995-05-20
 1995-05-21
 1995-05-22
 1995-05-23
 1995-05-24
 1995-05-25
 1995-05-26
 1995-05-27
 1995-05-28
 1995-05-29
 1995-05-30
 1995-05-31

In  [6]: intersect(a, b)

Out [6]: 7-element Array{Date{C<:Calendar},1}:
 1995-05-05
 1995-05-06
 1995-05-07
 1995-05-08
 1995-05-09
 1995-05-10
 1995-05-11

In  [7]: findin(a, b)

Out [7]: 7-element Array{Int64,1}:
  5
  6
  7
  8
  9
 10
 11
```

**Comment by cgroll** [comment]
that's strange! I did a Pkg.update() (I have version 0.1.3) and I am using julianightlies, which I am quite sure was updated today as well, but I still get wrong results as described above.

**Comment by quinnj** [comment]
Weird. Can you post the full output of `versioninfo(true)`?

**Comment by cgroll** [comment]
``` julia

julia> versioninfo(true)
Julia Version 0.3.0-prerelease
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
  WORD_SIZE: 64
           Ubuntu 12.04.4 LTS
  uname: Linux 3.8.0-39-generic #58~precise1-Ubuntu SMP Fri May 2 21:33:40 UTC 2014 x86_64 x86_64
Memory: 7.455715179443359 GB (2397.765625 MB free)
Uptime: 12242.0 sec
Load Avg:  1.8466796875  1.8701171875  1.2353515625
Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz: 
       speed         user         nice          sys         idle          irq
#1  2832 MHz      83643 s        768 s      33006 s    1080849 s          2 s
#2  1999 MHz      91586 s       1290 s      46707 s    1061295 s          0 s
#3  2832 MHz      79730 s       1032 s      27099 s    1090567 s          0 s
#4  1999 MHz      94454 s        661 s      37858 s    1067378 s          0 s

  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
Environment:
  TERM = dumb
  XDG_SESSION_PATH = /org/freedesktop/DisplayManager/Session0
  PATH = /usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
  DEFAULTS_PATH = /usr/share/gconf/ubuntu.default.path
  MANDATORY_PATH = /usr/share/gconf/ubuntu.mandatory.path
  XDG_SEAT_PATH = /org/freedesktop/DisplayManager/Seat0
  HOME = /home/chris

Package Directory: /home/chris/.julia/v0.3
11 required packages:
 - Cairo                         0.2.13
 - DataFrames                    0.5.4
 - Datetime                      0.1.3
 - Debug                         0.0.2
 - Distributions                 0.4.5
 - Gadfly                        0.2.7+             master
 - IJulia                        0.1.9
 - NLopt                         0.0.3
 - ODBC                          0.3.8
 - RDatasets                     0.1.1
 - Winston                       0.11.0
33 additional packages:
 - ArrayViews                    0.4.4
 - AssetMgmt                     0.0.0-             master (unregistered, dirty)
 - BinDeps                       0.2.12
 - Blocks                        0.0.3
 - Codecs                        0.1.0
 - Color                         0.2.9
 - Compose                       0.1.28
 - DataArrays                    0.1.8
 - DataStructures                0.2.13
 - Distance                      0.3.2
 - EconDatasets                  0.0.0-             develop (unregistered)
 - Econometrics                  0.0.0-             master (unregistered)
 - GZip                          0.2.12
 - HTTPClient                    0.1.4
 - Hexagons                      0.0.1
 - IniFile                       0.2.2
 - Iterators                     0.1.2
 - JSON                          0.3.5
 - LibCURL                       0.1.3
 - Loess                         0.0.2
 - Nettle                        0.1.4
 - NumericExtensions             0.6.2
 - NumericFuns                   0.2.3
 - PDMats                        0.1.2
 - Plotly                        0.0.0-             master (unregistered)
 - REPLCompletions               0.0.0
 - Reexport                      0.0.1
 - SortingAlgorithms             0.0.1
 - StatsBase                     0.3.12
 - TimeData                      0.1.1+             master
 - Tk                            0.2.11
 - URIParser                     0.0.2
 - ZMQ                           0.1.9
```

**Comment by quinnj** [comment]
Hmmm.........one more and then we can ask for some help. What's the output of `@which findin(a,b)`? You haven't defined a different `findin` anywhere have you?

**Comment by cgroll** [comment]
That's something I've already tried. It shows:

``` julia
julia> @which findin(a, b)
findin(a,b) at array.jl:1179
```

Also, I am now at a second computer, and I still have the same problem here as well. Maybe you could add a test case, in order to see, whether the problem exists at travis as well? Anyways, thanks for your effort.
